### ISSUE TITLE
Add Implied Yield to UI

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#1000]
See: https://github.com/delvtech/hyperdrive/issues/996

**Comment by DannyDelott** [comment]
Added to the Rust SDK: https://github.com/delvtech/hyperdrive/pull/998

Added to hyperdrive wasm bindings: https://github.com/delvtech/hyperdrive-bindings/pull/99

Currently waiting on a new Hyperdrive `v1.03` release so we can land the wasm bindings and begin using it in the frontend

**Comment by jalextowle** [comment]
Investigate market-wide implied yield (we could use the spot price to calculate the fixed rate)

**Comment by DannyDelott** [comment]
> Investigate market-wide implied yield (we could use the spot price to calculate the fixed rate)

We're currently passing a bondAmount of `1e18`, and using the current variable apy:

https://github.com/delvtech/hyperdrive-rs/blob/b78247d65ddecb39c9fc974fadd609ed83bd7c71/crates/hyperdrive-math/src/short/open.rs#L211-L226

**Comment by DannyDelott** [comment]
Related work: #1040 #1038
