### ISSUE TITLE
Integrate rust sdk method for previewCloseLong

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#1075]
Currently the `previewCloseXYZ` methods all use a simulateWrite for the preview. There are sdk methods for this calc now that we should switch over to:

- [x] previewCloseLong
- [x] previewCloseShort
- [ ] previewRemoveLiquidity
- [ ] previewRedeemWithdrawalShares

**Comment by dpaiton** [comment]
Closing since this is marked as Done.
