### ISSUE TITLE
Closed short still showing in UI

### ISSUE THREAD

**Issue by ryangoree** [delvtech/hyperdrive-frontend#1100]
I closed a long position, but can still see it in the open tab.

Transaction: https://sepolia.etherscan.io/tx/0x41dec17b5705a34bf125e7f70de9ff7b44312a4c6eff0152b0390156fb2ca959

![image](https://github.com/delvtech/hyperdrive-frontend/assets/3289505/3dab7127-2e96-40df-ab9d-5fd455086e5d)

![image](https://github.com/delvtech/hyperdrive-frontend/assets/3289505/2c76fe9b-1f8c-478f-a060-41783a2fa886)

**Comment by DannyDelott** [comment]
This might be a user error, the tx is for closing a long but the screenshots are of the Shorts tab.
