### ISSUE TITLE
Hyperdrive Changelog Page

### ISSUE THREAD

**Issue by jrhea** [delvtech/hyperdrive-frontend#1120]
We have updated the Deployment Registry to better support address discovery and a deployment changelog [Link to Registry PR](https://github.com/delvtech/hyperdrive/pull/1039). We need a webpage  that reads from the registry contract and generates two tables:

1. Pools
![image](https://github.com/delvtech/hyperdrive-frontend/assets/5555162/8fe86be4-df48-4109-b29e-67149786b1d1)

2. Factories
![image](https://github.com/delvtech/hyperdrive-frontend/assets/5555162/d90101e8-6171-4701-864d-d9dd847f2ac7)

Notes:
- app.hyperdrive.box/changelog
- all addresses are links to etherscan
- have a toggle for chain

**Comment by ryangoree** [comment]
A model for the registry was added to the SDK in #1252 and draft PR with a WIP changelog page can be found in #1257.

**Comment by ryangoree** [comment]
The tables have been added to the UI at the /chainlog route: https://app-staging.hyperdrive.box/chainlog
