### ISSUE TITLE
Add methods to ReadHyperdrive for getAllOpenLongs and getAllOpenShorts

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#1132]
Using `TransferSingle` events, return the list of assetIds and balances of the user's open longs and shorts.

This will be used in conjunction with new `getOpenLongDetails` and `getOpenShortDetails` methods for grabbing P&L, cost basis, etc.. if available.

example idea:
```ts
const openLongs = readHyperdrive.getAllOpenLongs(account);

const openLongDetails = openLongs
  .map(({ assetId, balance }) => {
    return {
      assetId,
      balance,
      // this will be undefined if no details can be calculated by getOpenLongDetails
      details: await readHyperdrive.getOpenLongDetails({ assetId });
  });

**Comment by DannyDelott** [comment]
Pausing on this to take on more priority work.

**Comment by dpaiton** [comment]
Closing since this is marked as Done.
