### ISSUE TITLE
Fix broken Current Value cell for large Long positions

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#1144]
If the long or short can't be fully closed (eg: it's too big), you get a `0` for the Current Value. :( 

We could calculate this via spot price instead of calling `previewCloseShort`. 

If it can't be fully closed we put a :warning: next to it w/ a tooltip that says, "This position cannot be fully closed at this time, current withdrawable amount is: xxx":

- [ ] Open Longs table
- [x] Open Shorts table

![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/ba133d27-f082-45d8-9eb5-777bc7d9fe09)

**Comment by DannyDelott** [comment]
We now show a warning letting users know the position cannot be fully closed.

Remaining work:
- [ ] Replace closeout value with a market estimate value (need sdk support)
- [ ] Use `calc_max_close` to estimate withdrawable balance (need sdk support)

**Comment by DannyDelott** [comment]
The market estimate value is in development in #1167.

 @MazyGio is reviewing the math and will post changes to that PR as needed.

**Comment by wakamex** [comment]
just created https://github.com/delvtech/hyperdrive-rs/issues/138 to tackle this in the rust SDK

I would prioritize `calc_max_close short` for mainnet, if possible

**Comment by DannyDelott** [comment]
> just created [delvtech/hyperdrive-rs#138](https://github.com/delvtech/hyperdrive-rs/issues/138) to tackle this in the rust SDK
> 
> I would prioritize `calc_max_close short` for mainnet, if possible

Agreed. This will depend on bandwidth from @jalextowle and @jrhea to complete.

I'm discovering this is especially important for when you want to close a position that cannot be fully closed at this time.

Here you have to click max, then adjust the input by hand to find how much you can close.

| Click max | then adjust by hand |
|---|---|
|![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/43443ecb-60db-4170-9563-34d00920af86)|![Image](https://github.com/delvtech/hyperdrive-frontend/assets/4524175/56b9e476-9810-4442-a323-9426e783e12e)|

**Comment by DannyDelott** [comment]
Shorts is done in #1167 

Longs should be done using the current `market price * bond_amount`. This shouldn't require any rust sdk support and can be done entirely on the client. I'm working on #1189 at the moment, but will circle back to this afterward.

**Comment by MazyGio** [comment]
Time elapsed and checkpoints must be taken into account as well, although it's true that the client can already fetch all of that. Both sides are now implemented in https://github.com/delvtech/hyperdrive-rs/pull/153 fwiw

**Comment by DannyDelott** [comment]
Downgrading priority from Urgent to High since multi-version pool support #1205 is higher priority.
