### ISSUE TITLE
Update app Footer

### ISSUE THREAD

**Issue by akhamisa** [delvtech/hyperdrive-frontend#1164]
**Resources**
- [Documentation](https://hyperdrive.box/docs)
- [Analytics](https://hyperdrive.blockanalitica.com/)
- [Security](https://docs-delv.gitbook.io/hyperdrive/security/security-for-the-hyperdrive-protocol)
- [Trading Bots](https://docs-delv.gitbook.io/hyperdrive/hyperdrive-trading-bots/quickstart)

**Ecosystem**
- Integrations [new page will be added to docs]
- Community [DELV's discord]
- [Governance](https://governance.element.fi/)

**About Us**
- [DELV](https://delv.tech/)
- [Blog](https://blog.delv.tech/)
- [Github](https://github.com/delvtech)

**Legal**
- [Terms of Use](https://delv-public.s3.us-east-2.amazonaws.com/delv-terms-of-service.pdf)
- [Privacy Policy](https://delv-public.s3.us-east-2.amazonaws.com/delv-privacy-policy.pdf)

Icons for Socials upfront:
- [X / Twitter](https://x.com/delv_tech)
- [Warpcast](https://warpcast.com/~/channel/delv)
- [Linkedin](https://ca.linkedin.com/company/delv-tech)

<img width="1092" alt="Screenshot 2024-06-10 at 3 34 04 PM" src="https://github.com/delvtech/hyperdrive-frontend/assets/16280283/b9fcd050-270c-497c-b181-02a5572ab8a2">

**Comment by akhamisa** [comment]
Attaching logo icons (favicons?) for socials.

Mazy is working on a new page in the Hyperdocs which will list out all of our integrations with descriptions and links to the respective project's websites/docs. We can link 'Integrations' in the Hyperdrive app footer to this page when ready.

[
![Warpcast logo icon](https://github.com/delvtech/hyperdrive-frontend/assets/16280283/7853eee1-f699-400a-a84a-4f27c6c99bdb)
![Linkedin logo icon](https://github.com/delvtech/hyperdrive-frontend/assets/16280283/c7ffd0ed-21c1-4c97-a701-fcefc802bc2b)
![Twiiter X logo icon](https://github.com/delvtech/hyperdrive-frontend/assets/16280283/29d288ed-4699-4c1c-a18c-583e090c6cfe)
](url)

**Comment by MazyGio** [comment]
Hey hey, the [Integrations](https://docs.hyperdrive.box/hyperdrive-for-developers/integrations) page is live in the docs, ready to add the link into the footer: https://docs.hyperdrive.box/hyperdrive-for-developers/integrations

cc/ @DannyDelott
