### ISSUE TITLE
Fix Lido shares/base conversion issues for Longs

### ISSUE THREAD

**Issue by MazyGio** [delvtech/hyperdrive-frontend#1168]
**Describe the bug**
1. When opening a Long on Lido stETH markets, the `Yield at Maturity` field is showing a different amount of yield than the bond amount suggests. The bond amount is correct (verified by opening a long and looking at the transaction), it's the yield field that needs to be adjusted.
2. On the positions table, the `Current Value` field shows a larger value than expected (larger than the bond amount).

**To Reproduce**
Open a Long on a Lido stETH market. Look at the numbers.

**Screenshots**
<img width="833" alt="_🏎・testnet-general___Element_DAO_-_Discord" src="https://github.com/delvtech/hyperdrive-frontend/assets/95626798/bb41d2c7-16c7-42b9-9b79-af3b4eb66013">

<img width="1242" alt="14d_ETH-Lido_stETH_-_Hyperdrive" src="https://github.com/delvtech/hyperdrive-frontend/assets/95626798/dce987c0-cc16-49c9-9de3-59c51f0152db">

**Comment by DannyDelott** [comment]
Closed in #1169
