### ISSUE TITLE
Gopher Bridge integration MVP

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#1191]
- [ ] Add a new `/bridge` route, and link to it from the Available Assets well if users have balances on other chains.
- [ ] Add a feature flag to expose the bridge option
- [ ] Xcalidraw diagram of user workflow when bridging assets
- [ ] Add `/packages/gopher` and build it in CI (check in the swagger.json only)
- [ ] Bring over useful code from demo

Swagger UI: https://gopher.test.buildwithsygma.com/swagger/index.html#/default

**Comment by jackburrus** [comment]
Gopher bridge integration de-prioritized
