### ISSUE TITLE
Add slippage control

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#327]
The interface should have a "gear" menu with slippage controls, similar to how Uniswap works: https://app.uniswap.org/#/swap

![Image](https://user-images.githubusercontent.com/4524175/258980985-c791c632-01d8-4f18-9cb4-210e3fc832fe.png)

**Comment by jalextowle** [comment]
We need this for longs, shorts, and LPs on open and closing

**Comment by DannyDelott** [comment]
Added to longs: #957 
Added to shorts: #968
