### ISSUE TITLE
Prepare Hyperdrive UI for Testnet

### ISSUE THREAD

**Issue by jalextowle** [delvtech/hyperdrive-frontend#844]
1. [x] Pool Discovery with DELV Registry (talk to @jalextowle for questions).
    - [x] Put registry on devnet (@jalextowle @mcclurejt)
3. [x] Set up process for issue and feedback tracking during testnet **Using #feedback-and-requests Discord channel to capture feedback, and we will move things into GH Issues as needed**
4. [x] Alchemy RPC URLs for Sepolia
5. [ ] Add website analytics (Not Blocking)
      - [ ] @DannyDelott and @jackburrus to make an informed decision/coordinate with @akhamisa and run it by @akhamisa, @CPSTL, and @jrhea 
      - [ ] What is the goal? Bounce rate, how long do they stay on the page, traffic, something else?
      - [ ] Traffic tracking from Twitter (for example)
6. [x] Wallet Connect (cc. @ryangoree)
      - [x] Configuration
      - [ ] Testing (need sanity check)
7. [x] ~Disable chain configuration modal for testnet (cc. @jackburrus)~
7. [ ] Rage cage issues (prioritized by urgency)
     - [x] Allowance mismatch when opening shorts (we'll need some padding)
     - [ ] Otherwise, mostly cosmetic and can be dealt with during the testnet (not blocking)
8. [x] UI Deployment
     - [x] Set up a production branch
     - [x] Deploy with Vercel
9. [x] Convert to LP Shares in LP tab #875

**Comment by akhamisa** [comment]
UI Analytics:

**What:**
We'd like to integrate an analytics tool into the Hyperdrive UI to be able to obtain user behavior insights which could inform further UI/UX improvements, and in addition, it could potentially seed some marcomms content once we're on mainnet. Examples of metrics to track:
- Avg session duration
- New vs. returning users
- Session conversion rate (leads to an on-chain tx)
- DAU / WAU / MAU
- Inbound traffic source
- Bounce rate
- Page analytics (clicks, drop-offs, time on page, etc.)
- ... + link to onchain insights + more

**Core Requirements:**
- Privacy focused / track anonymously
- Ability for user to opt-out of tracking
- Open source (ideal, but not a hard requirement)
- Simple integration, low eng lift, drop in scripts

**Shortlist** (rank ordered):
- Simple Analytics (used by Block Analitica): https://www.simpleanalytics.com/
- Plausible: https://plausible.io/
- Matomo: https://matomo.org/
- Safary (web3 native): https://www.safary.club/

**Status**: legal is reviewing ToS/Privacy for tools listed above
