### ISSUE TITLE
Update to generalized `vaultSharesToken` to the hyperdrive-js and app config

### ISSUE THREAD

**Issue by jalextowle** [delvtech/hyperdrive-frontend#858]
Blocked by v0.11.0 (@jalextowle)

**Comment by jalextowle** [comment]
This release was minted, so y'all should be good to go. Let me know if you have any issues!

**Comment by DannyDelott** [comment]
Done in [#862](https://github.com/delvtech/hyperdrive-frontend/pull/862)
