### ISSUE TITLE
Update Hyperdrive UI FAQs

### ISSUE THREAD

**Issue by MazyGio** [delvtech/hyperdrive-frontend#865]
Latest FAQs found [here](https://docs.google.com/document/d/1dJnJfcWpAuZe12oAjGl0reuLZKj7qcSrXKgF30iZdU4/edit#heading=h.ply08hn5ktq0). Already reviewed by Legal.

**Comment by ryangoree** [comment]
Done in #868 

@DannyDelott lmk otherwise
