### ISSUE TITLE
UI Web Analytics

### ISSUE THREAD

**Issue by jalextowle** [delvtech/hyperdrive-frontend#886]
- [x] Call with US/Canadian legal counsel (cc. greg, andrea)
- [x] Final legal approval re: Plausible's ToS
- [x] Updated DELV Privacy Policy
- [x] Banner re: updated Privacy Policy on delv.tech (@ryangoree)
- [x] ToS & Privacy Policy pop up modal on hyperdrive.trade (@DannyDelott)
- [x] Plausible account created ( @akhamisa @CPSTL)
- [x] Add Plausible code snippet to UI (@DannyDelott @jackburrus)
- [x] Add Plausible code snippet to DELV, Hyperdrive, Council. Gitbook websites (@ryangoree)

**Comment by jalextowle** [comment]
In legal review. Will take a week or two. @akhamisa @jrhea To investigate free options.

**Comment by jalextowle** [comment]
Should be hearing back today or tomorrow at the latest. We'll be going with plausible.io (demo in website)

**Comment by jalextowle** [comment]
@akhamisa @MazyGio to make the plausible account. Credentials in password manager and make sure the right people have permissions.

**Comment by akhamisa** [comment]
Still waiting on updated Privacy / ToS. Andrea has revised draft from external counsel. Hoping to have this finalized by end of this week or early next.

**Comment by akhamisa** [comment]
Andrea has provided updated draft of Privacy policy. She's asked Alim @DannyDelott @ryangoree @jrhea to review and provide feedback. I'll be reviewing today. See email w/subj: "User Analytics for Hyperdrive UI"

**Comment by akhamisa** [comment]
@DannyDelott @ryangoree heads-up legal requires the following:

"When you upload the new privacy policy, please add a banner on the delv.tech and hyperdrive.trade sites for 2 weeks after rolling out the new privacy policy. Something that reads: “We have updated our Privacy Policy. Please see our latest version here.” (with a link to the new privacy policy)."

**Comment by akhamisa** [comment]
Updated Privacy Policy received from legal. I'll send it over to both of you.

@DannyDelott please trigger a force confirm on the ToS & Privacy policy pop-up modal in the Hyperdrive UI. Include a link to the new Privacy Policy. 

@ryangoree please update the Privacy policy everywehere it needs to be updated: DELV, Hyperdrive, Council websites, and the Gitbook docs portal.

**Comment by ryangoree** [comment]
@akhamisa The [elfiverse.delv.tech](https://elfiverse.delv.tech/) has a pop-up similar to the Hyperdrive UI. I'm assuming re-triggering the modal like the Hyperdrive UI is sufficient, but please lmk otherwise.

<img width="1084" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/3289505/ff90760a-aea0-4800-ae31-ff5e39f286d5">

**Comment by ryangoree** [comment]
Banners have been added to the top of:
- https://delv.box/
- https://hyperdrive.box/
- https://council.delv.tech/

Issues to disable the banners after 2 weeks have been added to each repo:
- https://github.com/delvtech/delv-landing-page/issues/4
- https://github.com/delvtech/hyperdrive-website/issues/11
- https://github.com/delvtech/council-kit/issues/427

A meta task has also been added to the Hyperdrive board [here](https://github.com/orgs/delvtech/projects/13?pane=issue&itemId=63629807) to ensure they don't get forgotten.

For, https://elfiverse.delv.tech/, the Privacy Policy and ToS pop-up has been made to pop-up again for all users and requires that they click "Accept Terms" before dismissing.

**Comment by DannyDelott** [comment]
The hyperdrive trading ui is now showing the new privacy policy in the modal.

**Comment by akhamisa** [comment]
Ryan's added the Plausible code snippet to the delv.tech website. It's working great, I'm able to see the Plausible dashboard updating in real-time. 

I'm meeting with Charles shortly to upgrade our sub to a paid account so we can add multiple properties. I'll give Ryan and Danny a heads-up when we're ready to add all of the other sites, including the Hyperdrive UI.

**Comment by akhamisa** [comment]
**Hyperdrive UI**:
<script defer data-domain="testnet.hyperdrive.box" src="https://plausible.io/js/script.js"></script>

**Hyperdrive docs**:
<script defer data-domain="docs-delv.gitbook.io/hyperdrive" src="https://plausible.io/js/script.js"></script>

**DELV**:
<script defer data-domain="delv.tech" src="https://plausible.io/js/script.js"></script>

**Council**:
<script defer data-domain="council.delv.tech" src="https://plausible.io/js/script.js"></script>

**Elfiverse**:
<script defer data-domain="elfiverse.delv.tech" src="https://plausible.io/js/script.js"></script>

**Hyperdrive Analytics** (to be added by Block Analitica):
<script defer data-domain="hyperdrive.blockanalitica.com" src="https://plausible.io/js/script.js"></script>

**Comment by ryangoree** [comment]
Added to all except GitBook. For GitBook, I installed and configured the Plausible integration, but views don't seem to be showing up in the dashboard so I'm investigating.

**Comment by ryangoree** [comment]
It looks like it's working now. @akhamisa will confirm.

**Comment by ryangoree** [comment]
Docs is working now. Analytics is all that's left which will be added by BA.

**Comment by akhamisa** [comment]
Block Analitica has added the script to the Hyperdrive BA dashboard. We're all done!
