### ISSUE TITLE
Round market stats numbers using "K" and "M" suffixes

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#950]
The numbers are overflowing. We should update this to display values like: "264.43K DAI"

<img width="650" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/4524175/0b24e904-49c6-423b-8980-10055776c299">

**Comment by dpaiton** [comment]
Would be nice to do this or use comma separations in the `Available Markets` view as well.
<img width="289" alt="image" src="https://github.com/delvtech/hyperdrive-frontend/assets/153468/05822c84-6866-4234-8b14-2060b3fae8aa">

**Comment by jackburrus** [comment]
Closed in #955
