### ISSUE TITLE
Login via capsule causes the screen to freeze

### ISSUE THREAD

**Issue by jackburrus** [delvtech/hyperdrive-frontend#961]
![Image](https://github.com/delvtech/hyperdrive-frontend/assets/22210106/1d43e719-4128-440b-a5ae-637f66b82f83)

**Comment by DannyDelott** [comment]
Capsule team has been made aware of a potential issue on their side. It seems that when the capsule popup is opened, it sets `overflow: hidden` on the top-level html tag, but this style isn't removed when the popup is closed, causing the page to become unscrollable.

**Comment by DannyDelott** [comment]
This was solved in a later version of the capsule rainbowkit plugin
