### ISSUE TITLE
Fix missing Insufficient Liquidity label in Open Short

### ISSUE THREAD

**Issue by DannyDelott** [delvtech/hyperdrive-frontend#974]

**Comment by MazyGio** [comment]
The pools allow users to open shorts that are larger than the available liquidity (see screenshot).
![image](https://github.com/delvtech/hyperdrive-frontend/assets/95626798/8d540c64-0b84-494d-918f-01679dd95416)

IMO this is probably a bug in how "Available Liquidity" is calculated

**Comment by DannyDelott** [comment]
Closed in #1093 

Switched to calling this Idle instead, as the available liquidity isn't always the right metric for sizing trades.
