### ISSUE TITLE
Available Liquidity

### ISSUE THREAD

**Issue by jrhea** [delvtech/hyperdrive-frontend#977]
**Describe the bug**
When i hover over "available liquidity" it literally says that it is the "amount of capital that has been deployed by LPs into the pool"; however, it only seems to be showing the idle liquidity.

**Expected behavior**
Both liquidity numbers are useful for different reasons. 

**Screenshots**
![image](https://github.com/delvtech/hyperdrive-frontend/assets/5555162/efbed30f-c99d-4cbb-9d5d-31a82ed53e2a)

**Comment by jrhea** [comment]
![image](https://github.com/delvtech/hyperdrive-frontend/assets/5555162/a0994a4f-2b83-4855-93e1-74e661c866e6)

**Comment by MazyGio** [comment]
IMO we do want to show this "Idle liquidity" number, and I'd argue that it takes a higher priority for users in general than the "Total Liquidity" number. However, I'd also like to include the Total liquidity number somewhere.

One idea could be adding it as a subtext on the same field. Hover text could further clarify why there are two numbers, for newer users.

<img width="1057" alt="Hyperdrive___Fixed_and_Variable_Rates__Reimagined_" src="https://github.com/delvtech/hyperdrive-frontend/assets/95626798/4489eb10-4f98-4c85-ae1b-6183576c394c">

**Comment by jrhea** [comment]
The present value of the liquidity in the pool is maybe more useful
